FROM golang:alpine as builder

RUN apk update && apk add git && apk add ca-certificates
RUN adduser -D -g '' appuser
COPY ./imageservice /app/imageservice
COPY ./healthchecker /app/healthchecker
WORKDIR /app/imageservice/
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o /go/bin/imageservice-linux-amd64
RUN cd /app/healthchecker; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o /go/bin/healthchecker-linux-amd64
RUN chown -R appuser:appuser /go

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/imageservice-linux-amd64 /go/bin/imageservice-linux-amd64
COPY --from=builder /go/bin/healthchecker-linux-amd64 /go/bin/healthchecker-linux-amd64

HEALTHCHECK --interval=5s --timeout=5s CMD [ "/go/bin/healthchecker-linux-amd64", "-host=http://127.0.0.1:8080" ] || exit 1

USER appuser
ENTRYPOINT ["/go/bin/imageservice-linux-amd64"]

