FROM golang:alpine as builder

RUN apk update && apk add git && apk add ca-certificates
RUN adduser -D -g '' appuser
COPY ./gelftail /app/gelftail
WORKDIR /app/gelftail/
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o /go/bin/gelftail-linux-amd64
RUN chown -R appuser:appuser /go

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/gelftail-linux-amd64 /go/bin/gelftail-linux-amd64

EXPOSE 12201/udp

USER appuser
ENTRYPOINT ["/go/bin/gelftail-linux-amd64"]

