server:
    port: 8888
    #ssl:
    #    key-store: classpath:server.jks
    #    key-store-password: password
    #    key-password: password

spring:
    cloud:
        config:
            server:
                git:
                    uri: ${CONFIG_SERVER_GIT_URI:/config-repo}
        bus:
            trace:
                enabled: true
    rabbitmq:
        host: rabbitmq
        port: 5672

encrypt:
    key-store:
        location: file:/server.jks
        password: letmein
        alias: mytestkey
        secret: changeme
