server:
  port: 8888
  #ssl:
  #  key-store: classpath:server.jks
  #  key-store-password: letmein
  #  key-password: changeme

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI:/config-repo}
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672

